### ISSUE TITLE
web-assets:assets vs web-stage

### ISSUE THREAD

**Issue by vjkoskela** [sbtrun-maven-plugin/sbtrun-maven-plugin#8]
I am trying to invoke the gzip plugin to create gzip versions of my assets. I have based my pom and sbt configuration on the documentation and example. While the documentation and examples invoke sbtrun with args of "web-assets:assets"

e.g.
https://sbtrun-maven-plugin.github.io/sbtrun-maven-plugin/1.0.0-beta3/usage.html

e.g.
https://github.com/sbtrun-maven-plugin/sbtrun-maven-test-projects/blob/master/play23/scala/zentasks/pom.xml#L129

This unfortunately does not work for me. Further, invoking activator with this goal also does not process the resources. However, invoking the web-stage target does work. While I am satisfied with this thus far, I wanted to check if I was missing something obvious.

Thanks for the great plugin!
Ville

project/plugins.sbt
```
// Comment to get more information during initialization
logLevel := Level.Warn

// The Typesafe repository
resolvers += Resolver.typesafeRepo("releases")

addSbtPlugin("com.typesafe.sbt" % "sbt-web" % "1.2.2")

addSbtPlugin("com.typesafe.sbt" % "sbt-gzip" % "1.0.0")
```

project/build.properties
```
sbt.version=0.13.9
```

build.sbt
```
scalaVersion := "2.11.7"

lazy val main = (project in file("."))
  .enablePlugins(SbtWeb)
  .settings(
    sourceDirectory in Assets := baseDirectory.value / "app/assets",
    resourceDirectory in Assets := baseDirectory.value / "public",
    target := baseDirectory.value / "target/sbt",
    includeFilter in gzip := "*",
    pipelineStages := Seq(gzip)
  )
```

pom.xml
```
      <plugin>
        <groupId>com.google.code.sbtrun-maven-plugin</groupId>
        <artifactId>sbtrun-maven-plugin</artifactId>
        <version>1.0.0-beta3</version>
        <executions>
          <execution>
            <id>compile-assets</id>
            <phase>generate-resources</phase>
            <goals>
              <goal>run</goal>
            </goals>
            <configuration>
              <args>web-stage</args> <!-- Only Difference? -->
            </configuration>
          </execution>
        </executions>
      </plugin>
```

**Comment by gslowikowski** [comment]
Hi

Perhaps `web-stage` task processes pipeline and `assets` task doesn't.
I never tested assets pipelines, so `assets` was always enough for all my test projects.

Just use whatever task you need.
